global:
  dockerRegistrySecret: "" # leave empty if public repo
  baseRepo: "quay.io/datashim"
  arch: "amd64"
  type: "k8s"
  namespaceYaml: false

  sidecars:
    kubeletPath: "/var/lib/kubelet"
    baseRepo: "quay.io/k8scsi"
    images:
      externalAttacher:
        image: "csi-attacher"
        tag: "v2.2.0"
      nodeDriverRegistrar:
        image: "csi-node-driver-registrar"
        tag: "v1.2.0"
      clusterDriverRegistrar:
        image: "csi-cluster-driver-registrar"
        tag: "v1.0.1"
      externalProvisioner:
        image: "csi-provisioner"
        tag: "v2.0.2"

csi-nfs-chart:
# baseRepo: "anotherrepo"
# dockerRegistrySecret: "anothersecret"
  csinfs:
    image: "csi-nfs"
    tag: "latest"
  sidecars: {} # in case you want to force override regardless of the csi-nfs-chart/values.yaml

csi-s3-chart:
  baseRepo: "renku"
# dockerRegistrySecret: "anothersecret"
# mounter: "goofys"
  csis3:
    image: "datashim-csi-s3"
    tag: "0.1.1-rc4"
  sidecars: {} # in case you want to force override regardless of the csi-s3-chart/values.yaml

csi-h3-chart:
  baseRepo: "carvicsforth"
# dockerRegistrySecret: "anothersecret"
  csih3:
    image: "csi-h3"
    tag: "v1.2.0"
  sidecars: {} # in case you want to force override regardless of the csi-s3-chart/values.yaml

dataset-operator-chart:
  baseRepo: "renku"
# dockerRegistrySecret: "anothersecret"
  generatekeys:
    image: "datashim-generate-keys"
    tag: "0.1.1-rc4"
  datasetoperator:
    image: "datashim-dataset-operator"
    tag: "0.1.1-rc4"
