name: Release Chart

on:
  create:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+**"


jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout whole repo
        uses: actions/checkout@v2
        with:
          repository: 'datashim-io/datashim'
      - name: Install chart releaser
        run: |
          curl -L https://github.com/helm/chart-releaser/releases/download/v1.2.1/chart-releaser_1.2.1_linux_amd64.tar.gz | tar -xz -C /usr/local/bin/
          chmod a+x /usr/local/bin/cr
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.0
      - name: Package chart
        run: |
          helm package ./chart -u -d ./.helm-deploy/
      - name: Set CR env values
        run: |
          echo "CR_OWNER=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')" >> $GITHUB_ENV
          echo "CR_GIT_REPO=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')" >> $GITHUB_ENV
          echo "CR_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: Checkout gh pages repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: gh-pages-chart
          path: .gh-pages
      - name: Publish chart with CR
        run: |
          cr upload --skip-existing --package-path .helm-deploy
          cd .gh-pages
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          cr index --charts-repo https://swissdatasciencecenter.github.io/datashim/ --push --package-path ../.helm-deploy --index-path ./index.yaml --pages-branch gh-pages-chart